### ISSUE TITLE
Error opening files or connecting ftp on FreeBSD

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [icecoder/ICEcoder#742]
Hello,
I get an error opening files or connecting via ftp. My documentRoot is set to "/" and DevMode => true.
My error-log.txt:
`
[21-Jun-2018 08:10:05 UTC] PHP Warning:  fileperms(): stat failed for ///sys in /usr/local/www/apache24/data/html/code/lib/get-branch.php on line 199
[21-Jun-2018 09:08:13 UTC] PHP Warning:  fileperms(): stat failed for ///sys in /usr/local/www/apache24/data/html/code/lib/get-branch.php on line 199
[21-Jun-2018 09:11:00 UTC] PHP Warning:  fileperms(): stat failed for ///sys in /usr/local/www/apache24/data/html/code/lib/get-branch.php on line 199
[21-Jun-2018 09:11:38 UTC] PHP Warning:  Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII' (this will throw an Error in a future version of PHP) in /usr/local/www/apache24/data/html/code/lib/settings.php on line 182
[21-Jun-2018 09:11:40 UTC] PHP Warning:  Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII' (this will throw an Error in a future version of PHP) in /usr/local/www/apache24/data/html/code/lib/settings.php on line 182
[21-Jun-2018 09:11:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ftp_connect() in /usr/local/www/apache24/data/html/code/lib/ftp-control.php:7
Stack trace:
#0 /usr/local/www/apache24/data/html/code/lib/get-branch.php(127): ftpStart()
#1 {main}
  thrown in /usr/local/www/apache24/data/html/code/lib/ftp-control.php on line 7
[21-Jun-2018 09:11:46 UTC] PHP Warning:  Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII' (this will throw an Error in a future version of PHP) in /usr/local/www/apache24/data/html/code/lib/settings.php on line 182
[21-Jun-2018 09:11:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ftp_connect() in /usr/local/www/apache24/data/html/code/lib/ftp-control.php:7
Stack trace:
#0 /usr/local/www/apache24/data/html/code/lib/get-branch.php(127): ftpStart()
#1 {main}
  thrown in /usr/local/www/apache24/data/html/code/lib/ftp-control.php on line 7
[21-Jun-2018 09:11:50 UTC] PHP Warning:  Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII' (this will throw an Error in a future version of PHP) in /usr/local/www/apache24/data/html/code/lib/settings.php on line 182
[21-Jun-2018 09:11:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ftp_connect() in /usr/local/www/apache24/data/html/code/lib/ftp-control.php:7
Stack trace:
#0 /usr/local/www/apache24/data/html/code/lib/get-branch.php(127): ftpStart()
#1 {main}
  thrown in /usr/local/www/apache24/data/html/code/lib/ftp-control.php on line 7
[21-Jun-2018 09:11:52 UTC] PHP Warning:  Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII' (this will throw an Error in a future version of PHP) in /usr/local/www/apache24/data/html/code/lib/settings.php on line 182
[21-Jun-2018 09:11:52 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ftp_connect() in /usr/local/www/apache24/data/html/code/lib/ftp-control.php:7
Stack trace:
#0 /usr/local/www/apache24/data/html/code/lib/get-branch.php(127): ftpStart()
#1 {main}
  thrown in /usr/local/www/apache24/data/html/code/lib/ftp-control.php on line 7
[21-Jun-2018 09:12:19 UTC] PHP Warning:  Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII' (this will throw an Error in a future version of PHP) in /usr/local/www/apache24/data/html/code/lib/settings.php on line 182
[21-Jun-2018 09:12:25 UTC] PHP Warning:  fileperms(): stat failed for //sys in /usr/local/www/apache24/data/html/code/lib/get-branch.php on line 199
[21-Jun-2018 10:03:32 UTC] PHP Warning:  fileperms(): stat failed for //sys in /usr/local/www/apache24/data/html/code/lib/get-branch.php on line 199`

**Comment by mattpass** [comment]
Hmmm OK I will look into this. It's trying to get file/dir permissions and unable to, so a PHP warning. Need to test if it can get them first on the line above the erroring line that tries to use them I suspect.

**Comment by mattpass** [comment]
Have decided to remove FTP from ICEcoder as it's just not a modern solution to data transfer these days. Far better solutions out there and can be part of ICEcoder in future.
