### ISSUE TITLE
Rename dir in which a file is open as a tab error

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#844]
Report from user:

When I rename a directory in which I have files open, it creates an error if I try to save the files after renaming the directory.

PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, bool$
Stack trace:
#0 /var/www/html/ICEcoder/classes/File.php(72): strpos(false, '/var/www/...')
#1 /var/www/html/ICEcoder/lib/file-control.php(59): ICEcoder\File->check()
#2 {main}
  thrown in /var/www/html/ICEcoder/classes/File.php on line 72

**Comment by mattpass** [comment]
This is working without error now - an edge case to handle tho... if  you rename an open file and type a new path for it in the dialog box, it moves it fine but doesn't add it in new dir or remove it from old dir.

**Comment by mattpass** [comment]
This is still an issue to resolve.

**Comment by mattpass** [comment]
All of this is now resolved and working great so closing.
